/**
 * Manager headshots.
 *
 * Kept separate from fixtures.json (which is regenerated by
 * make_fixtures_082926.py / the real-data import) so photos survive a
 * data refresh. Add a slug -> path entry here as photos come in; anyone
 * without an entry falls back to the letter-avatar in the UI.
 *
 * Each manager has a small thumbnail (480x480, public/images/managers/)
 * used in lists and headers, and a larger full-res version
 * (900x900, public/images/managers/full/) shown in the click-to-enlarge
 * lightbox.
 */
export const managerPhotos: Record<string, string> = {
  "andrew-briscoe": "/images/managers/andrew-briscoe.png",
  "andrew-king": "/images/managers/andrew-king.png",
  "greg-stiefvater": "/images/managers/greg-stiefvater.png",
  "jack-muchnick": "/images/managers/jack-muchnick.png",
  "jeff-ready": "/images/managers/jeff-ready.png",
  "john-briscoe": "/images/managers/john-briscoe.png",
  "loren-muchnick": "/images/managers/loren-muchnick.png",
  "marc-muchnick": "/images/managers/marc-muchnick.png",
  "ryan-muchnick": "/images/managers/ryan-muchnick.png",
  "scott-zide": "/images/managers/scott-zide.png",
  "steve-king": "/images/managers/steve-king.png",
  "will-briscoe": "/images/managers/will-briscoe.png",
};

export const managerPhoto = (slug: string): string | undefined => managerPhotos[slug];

export const managerPhotoFull = (slug: string): string | undefined => {
  const thumb = managerPhotos[slug];
  return thumb ? thumb.replace("/images/managers/", "/images/managers/full/") : undefined;
};
